@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Dec 09 22:09:28 -0500 2019
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim CPU_Test_behav -key {Behavioral:sim_1:Functional:CPU_Test} -tclbatch CPU_Test.tcl -view C:/Users/Taylan Unal/iCloudDrive/Fall2019/CMPEN331/Labs/Lab5_Unal/CPU_Test_behav.wcfg -log simulate.log"
call xsim  CPU_Test_behav -key {Behavioral:sim_1:Functional:CPU_Test} -tclbatch CPU_Test.tcl -view C:/Users/Taylan Unal/iCloudDrive/Fall2019/CMPEN331/Labs/Lab5_Unal/CPU_Test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
